const { Router } = require('express')
const router = Router()
const userController = require('../controllers/user.controller')
const verify = require('../middleware/loggedIn')
router.get('/', verify.loggedIn, userController.getAllUsers)
router.get('/signup', userController.signUpGet)
router.post('/signup', userController.signUpPost)
router.get('/login', userController.logInGet)
router.post('/login', userController.logInPost)
router.get('/logout', verify.loggedIn, userController.logOut)
router.get('/update/:id', verify.loggedIn, userController.getUpdateUser)
router.post('/update/:id', verify.loggedIn, userController.postUpdateUser)
router.get('/delete/:id', verify.loggedIn, userController.deleteUser)

module.exports = router